### ISSUE TITLE
1.19.2 Release

### ISSUE THREAD

**Issue by piebaker** [lukebemish/revamped_phantoms#10]
**Is your feature request related to a problem? Please describe.**
This mod is awesome. I wish it was on newer versions of MC. 

**Describe the solution you'd like**
Update to 1.19.2 fabric

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lukebemish** [comment]
Revamped Phantoms is now updated to 1.20.4, skipping in-between versions; I have no plans to port to them at present.
