### ISSUE TITLE
Port Revamped Phantoms to Forge 1.20.1

### ISSUE THREAD

**Issue by averydoesstuff** [lukebemish/revamped_phantoms#12]
"Revamped Phantoms is now updated to 1.20.4, skipping in-between versions; I have no plans to port to them at present."

When I read this, I was perplexed that there isn't a Forge port dedicated for 1.20.1. Across both Modrinth and CurseForge, Forge 1.20.1 additions are almost always unmatched in total downloads, consistently ranking as the Minecraft version with the greatest compatibility for current players and mods/packs.

Thank you for making this mod; I just wanted to bring this detail to your attention!

**Comment by lukebemish** [comment]
I have no plans to port to forge 1.20.1 at this time. I make mods as a hobby, for the version of the game that I'm playing -- thus, I only very very rarely backport anything.
