### ISSUE TITLE
[Feature] Make vanilla compatible

### ISSUE THREAD

**Issue by CorneliusCornbread** [lukebemish/revamped_phantoms#13]
There are many server side mods that don't require the client to add their or even use Fabric to join the server. This mod unfortunately doesn't allow this to work after adding it to the server, requiring clients to add it on their end. Is there a way this mod could be made server only? Allowing it to be used like a plugin for Fabric Vanilla servers.

**Comment by lukebemish** [comment]
This mod adds/changes things that require rendering and additions to vanilla registries, so... no? You can't make a mod that has client-side effects server-only.
