### ISSUE TITLE
Daytime Phantom Spawn

### ISSUE THREAD

**Issue by yourcraft0** [lukebemish/revamped_phantoms#3]
Preface:
I use Forge and Optifine including 125~ mods some of which affects the behavior of mobs and mods that add new mobs into the game. I do not make modpacks nor use datapacks. So far this mod does not crash the game nor conflict with any other mods installed.

Issue:
At the first time of spawning into a new world, according to the Xaero's Minimap, it is at 6 am in game phantoms will spawn only to burn up. Only a few like 1 to 3 will appear up until before 8 am. 
*Like clockwork 1 to 3 phantoms will then spawn at 1 pm, to burn up. 
*At 4 pm 1 to 3 will appear, then burn up.  
*At around pass 6 pm (6:16 to 6:20 pm) they will spawn and then unto the night. The cycle repeats to the next in game day. 

Overview:
*The phantoms do spawn in dark spaces within caves. 
*The phantoms do spawn during the rain and thunderstorms. 
*The phantoms do carry and manage to kill any mob they encounter. Occasionally one will survive when the phantom doesn't drop it high enough. 
*Depending on when I do not sleep sometimes a few phantoms will also appear at 9 am the next day in addition to the previously mentioned hours they appear. It is infrequent though.

**Comment by lukebemish** [comment]
Hello,

What version are you on? If you are not already, please update to 0.1.2.

**Comment by yourcraft0** [comment]
> Hello,
> 
> What version are you on? If you are not already, please update to 0.1.2.

I have the [v0.1.1c]. Thank you and sorry for the trouble.

**Comment by lukebemish** [comment]
Cool. If the issue keeps happening, attach your mod list. Otherwise I'm going to close this.

**Comment by yourcraft0** [comment]
> Cool. If the issue keeps happening, attach your mod list. Otherwise I'm going to close this.
[mods.txt](https://github.com/lukebemish/revamped_phantoms/files/7998945/mods.txt)

**Comment by yourcraft0** [comment]
The update helped no more daytime phantoms
