### ISSUE TITLE
[ENHANCEMENT] Add way to stop phantoms from attacking specific mobs

### ISSUE THREAD

**Issue by Shroomy281** [lukebemish/revamped_phantoms#4]
While playing with Alex's Mobs, phantoms were able to pick up mobs that seemed too big for them to realistically attack, such as bison or even whales. The easiest way to fix this, I assume, would be to have a mob attacking blacklist in the config.

**Comment by lukebemish** [comment]
I'll add attackable mobs as an entity tag instead once I have some free time.

**Comment by lukebemish** [comment]
Entity tags aren't really great for this, so I'll just add a blacklist.

**Comment by lukebemish** [comment]
Should be implemented in v0.2.2
