### ISSUE TITLE
[BUG] Issue with... Revamped Phantoms

### ISSUE THREAD

**Issue by zachsai** [lukebemish/revamped_phantoms#5]
**Describe the bug**
![image](https://user-images.githubusercontent.com/63996164/158447790-70cb2718-fa9d-4036-994b-0ee18ce9c2da.png)
https://pastebin.com/cVh2nLZR
**To Reproduce**
Launch with same mods? Apparently your hacks are failing

**Expected behavior**
not instant crash on game boot

**Screenshots**

**Version:**
 - Forge 40.0.15
 - vX.Y.Z

**Additional context**

**Comment by lukebemish** [comment]
Logs and the version or nothing I can do

**Comment by lukebemish** [comment]
That is... Weird. Said hacks should not be failing. Can probably fix it in a few minutes

**Comment by lukebemish** [comment]
Will be fixed on the next release in an hour or so
