### ISSUE TITLE
Config for how many days until phantoms spawn

### ISSUE THREAD

**Issue by Killercrab432** [lukebemish/revamped_phantoms#7]
Love the picking up feature but i do think it might be a bit too strong against early game players on a server when people cant sleep as often, perhaps create a config option to change the amount of nights without sleep required for phantoms to start spawning instead of the default 4 nights, i think it would be a great feature to include. you could even include a feature making it so phantoms dont start stunning you until x amount of nights have passed with no sleep and same with the picking up feature making them progressively stronger the longer you go without sleeping

**Comment by lukebemish** [comment]
Implemented in 1.20.4; the new `base_restlessness` config option is a number of ticks without sleep that a player that just slept is considered to have.
