### ISSUE TITLE
[BUG] Issue with Shockwave method - out of bounds entity index

### ISSUE THREAD

**Issue by wildficus** [lukebemish/revamped_phantoms#9]
**Describe the bug**
revamped_phantoms.entity.Shockwave.method

**To Reproduce**
Phantom to shoot shockwave at carriage entity from Transportables mod.

**Expected behavior**
Modpack DeathDusk. Server crashed when a phantom shot a shockwave at a carriage entity from Transportables mod.
Keeps crashing after the server restarted/ difficulty changed to peacefull.

**Screenshots**
Not applicable

**Version:**
 - fabric-api-0.53.4+1.18.2.jar
 - revamped_phantoms-fabric-0.2.3.jar

**Additional context**
Crash report here.
[crash-2022-05-28_21.26.23-server.txt](https://github.com/lukebemish/revamped_phantoms/files/8792160/crash-2022-05-28_21.26.23-server.txt)

**Comment by lukebemish** [comment]
This is not a bug caused by Revamped Phantoms. Some other mod of yours, or possibly a combination of mods, is messing with the `LivingEntity#hurt` method in a way that breaks things.
